### ISSUE TITLE
新版本的编译问题

### ISSUE THREAD

**Issue by w0330t** [wechat-miniprogram/api-typings#69] opened 2019-08-24 12:32 UTC
我在编译的时候报如下错误：
```
/node_modules/miniprogram-api-typings/types/wx/lib.wx.api.d.ts(14566,15): error TS2451: Cannot redeclare block-scoped variable 'console'.
/node_modules/typescript/lib/lib.dom.d.ts(18257,13): error TS2451: Cannot redeclare block-scoped variable 'console'.
```
请问如何解决这个问题啊？

**Comment by milewski** [comment] 2019-08-25 02:44
Version `2.8.0-2` is broken.. rollback to version `2.8.0-1` it works

**Comment by John0King** [comment] 2019-08-25 13:51
@w0330t 看 #66

**Comment by wechat-miniprogram-admin** [comment] 2019-08-26 06:49
Duplicate of #66 . Since this typings is for AppService that runs without DOM APIs, `console` is actually provide by the miniprogram framework and thus typings of `console` was added to `2.8.0-2`. Check if `lib: [ 'dom' ]` exists in your compile config and remove it.

**Comment by milewski** [comment] 2019-08-26 10:55
Removing DOM does fix the issue 👍

**Closed** 2019-08-30 05:57 UTC
