### ISSUE TITLE
无法重新声明块范围变量“console”

### ISSUE THREAD

**Issue by q716015** [wechat-miniprogram/api-typings#103] opened 2020-02-09 23:37 UTC
无法重新声明块范围变量“console”。ts(2451)

lib.dom.d.ts(19661, 13): 'console' was also declared here.

lib.wx.api.d.ts:15775:15 - error TS2451: Cannot redeclare block-scoped variable 'console'.

declare const console: WechatMiniprogram.Console

**Comment by Mister-Hope** [comment] 2020-02-10 01:50
See #66. Why don't you check the issues before opening a new one

**Comment by SgLy** [comment] 2020-02-10 04:22
Duplicate of #66 .

**Closed by SgLy** 2020-02-10 04:22 UTC
